### ISSUE TITLE
cannot load such file -- jekyll/post in Jekyll 3.0

### ISSUE THREAD

**Issue by calebgrove** [lawrencewoodman/related_posts-jekyll_plugin#9]
This plugin is thowing this error message in Jekyll 3.0 and preventing the website from being built:

```
file: /Users/Caleb/foo/bar/_config.yml
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- jekyll/post (LoadError)
from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /Users/Caleb/foo/bar/_plugins/related_posts.rb:3:in `<top (required)>'
from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:74:in `each'
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:73:in `each'
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:97:in `setup'
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:49:in `initialize'
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `new'
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `process'
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/bin/jekyll:17:in `<top (required)>'
from /usr/local/bin/jekyll:23:in `load'
from /usr/local/bin/jekyll:23:in `<main>'
```

It looks like a problem with `require 'jekyll/post'`, but then again, I don't know enough Ruby to know what I'm talking about.

See: https://talk.jekyllrb.com/t/error-messages-when-upgrading-to-3-0-on-mac-os-x/1398

**Comment by lawrencewoodman** [comment]
You could try looking at [issue 6](https://github.com/LawrenceWoodman/related_posts-jekyll_plugin/issues/6) which mentions a fork of the plugin which may work for you.
